# Generated by Django 4.2 on 2024-12-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_address_order_orderitem_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='account.address'),
            preserve_default=False,
        ),
    ]
